---
groups:
  persistence:
    - redis
    - mysql
  core:
    - devise
    - devise_worker
    - spring_wizard
    - nginx
    - frontend
    - persistence
  apis:
    - gresb
    - gresb_worker
    - measurabl_reports
    - measurabl_reports_worker
  utilities:
    - cohort_report_scorer
    - estar_sync
    - pusher
  workers:
    - devise_worker
    - gresb_worker
    - measurabl_reports_worker
  surveys:
    - limesurvey
    - nginx_lime
  climate_risk:
    - climate_risk_import
    - 427_connector
    - mongo

default-group: core

services:
  # Devise entries
  devise:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/devise
    tag: "9b6e927"
    compose:
      environment:
        RAILS_RUN_MIGRATIONS: "false"
        DATABASE_ZUORA_HOST: "mysql"
        VERSION_JSON_PATH: "/frontend/release/version.json"
      volumes:
        - "devise_logs:/devise/log:delegated"
        - "frontend-export:/frontend/release:ro"
    container_port: 3000
  devise_worker:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/devise
    tag: "9b6e927"
    compose:
      environment:
        RAILS_WORKER_MODE: "true"
        RAILS_RUN_MIGRATIONS: "false"
        DATABASE_ZUORA_HOST: "mysql"
  # GRESB entries
  gresb:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/gresb_qual_api
    tag: master
    alias: "gresb-qual-api"
    container_port: 3000
    compose:
      environment:
        RAILS_RUN_MIGRATIONS: "true"
  gresb_worker:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/gresb_qual_api
    tag: master
    compose:
      environment:
        RAILS_WORKER_MODE: "true"

  limesurvey:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/limesurvey
    tag: master

  # frontend
  frontend:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/frontend
    tag: master
    compose:
      environment:
        NPM_START: "false"
      randomkey: "randomvalue"
      volumes:
        - "frontend-export:/frontend/export:delegated"
  measurabl_reports:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/msr_reports_api
    tag: master
    container_port: 3000
    compose:
      environment:
        RAILS_RUN_MIGRATIONS: "true"
  measurabl_reports_worker:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/msr_reports_api
    tag: master
    compose:
      environment:
        RAILS_WORKER_MODE: "true"
  cohort_report_scorer:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/cohort-report-scorer
    tag: "47ca40b"
    container_port: 10019
    compose:
      environment:
        AWS_ACCESS_KEY: x
        AWS_SECRET_KEY: x

  spring_wizard:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/wizard
    tag: "47ca40b"
    alias: "spring-wizard" # wizard url validator rejects hostnames with underscores
    container_port: 10007
    compose:
      memory: 2G
      cpus: 3.0

  pusher:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/pusher
    tag: "47ca40b"

  estar_sync:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/estar_sync
    tag: "47ca40b"
    compose:
      memory: 2G

  automated_stats:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/automated_stats
    tag: master

  climate_risk_import:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/climate-risk-import
    tag: "47ca40b"

  427_connector:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/msr_427connector
    tag: master
    container_port: 10011
    alias: "427-connector"

  archer:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/archer
    tag: '47ca40b'
    container_port: 10027

  nginx:
    # yamllint disable-line rule:line-length
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/msr_nginx_local
    tag: master
    compose:
      volumes:
        - "frontend-export:/frontend/release:ro"
    container_port: 8080
    host_port: 8080
    depends_on:
      - devise

  nginx_lime:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/msr_nginx_local
    tag: master
    alias: nginx-lime
    container_port: 9000
    depends_on:
      - limesurvey

  redis:
    repository: docker.io/library/redis
    tag: latest
    container_port: 6379
  mysql:
    repository: 402295273060.dkr.ecr.us-west-2.amazonaws.com/measurabl/msr_mysql_local
    tag: "5.7-5554b41-w-47ca40b-d-9b6e927"
    command: --character-set-server=utf8mb4
    compose:
      cpus: 2.2
      memory: 1G
      label:
        com.measurabl: "database"
      volumes:
        - "mysql-data:/var/lib/mysql:delegated"
    container_port: 3306
  mongo:
    repository: docker.io/library/mongo
    tag: latest
    container_port: 27017

# yamllint disable rule:empty-values
volumes:
  frontend-export:
    driver: "local"
  mysql-data:
    driver: "local"
